name: Deploy to royalclient.omkarbet prod SERVER New Test...

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install

    - name: Build client for royalclient.omkarbet prod
      run: npm run build:prod

    - name: Setup SSH for royalclient.omkarbet prod Server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_1_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_1_HOST }} >> ~/.ssh/known_hosts

    - name: Debug Deployment Information for betday prod
      run: |
        echo "HOST: ${{ secrets.SERVER_1_HOST }}"
        echo "USERNAME: ${{ secrets.SERVER_1_USERNAME }}"
        echo "PORT: ${{ secrets.SERVER_1_PORT }}"

    - name: Test SSH Connectivity for betday prod
      run: |
        nc -zv ${{ secrets.SERVER_1_HOST }} ${{ secrets.SERVER_1_PORT }}

    - name: Deploy to royalclient.omkarbet prod Server
      env:
        HOST: ${{ secrets.SERVER_1_HOST }}
        USERNAME: ${{ secrets.SERVER_1_USERNAME }}
        PORT: ${{ secrets.SERVER_1_PORT }}
      run: |
        rsync -avz -e "ssh -p $PORT" dist/ $USERNAME@$HOST:/var/www/royalclient.omkarbet.com/public_html
